"""Build notebook versions of the course (docs/*.md -> course/*.ipynb).

The Markdown files in docs/ are the source of truth. This script turns each
chapter into a Jupyter notebook: explanations become Markdown cells (one per
section) and every ```python block becomes a runnable code cell.

Usage (from the project folder, runs inside the Docker environment):
    docker compose run --rm lab python scripts/build_course_notebooks.py          # (re)build course/
    docker compose run --rm lab python scripts/build_course_notebooks.py --check  # fail if course/ is out of date
"""

import platform
import re
import sys
from pathlib import Path

import nbformat

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
COURSE = ROOT / "course"

# The how-to guide, the course chapters and the glossary.
# docs/claude-skills.md is tooling, not course material.
SOURCES = [DOCS / "how-to.md", *sorted(DOCS.glob("0*.md")), DOCS / "glossary.md"]
CONVERTED = {path.name for path in SOURCES}

LINK = re.compile(r"\]\(([^)\s]+)\)")
INLINE_CODE = re.compile(r"(`[^`]*`)")


def fix_link(match: re.Match) -> str:
    """Point links to other chapters at their notebook versions.

    Links to other docs/ files that have no notebook version keep pointing at docs/.
    """
    target = match.group(1)
    file_part, hash_sign, anchor = target.partition("#")
    if file_part in CONVERTED:
        target = file_part.removesuffix(".md") + ".ipynb" + hash_sign + anchor
    elif file_part.endswith(".md") and "/" not in file_part:
        target = f"../docs/{target}"
    return f"]({target})"


def prepare_markdown_line(line: str) -> str:
    """Protect $ outside inline code and fix links.

    Jupyter renders text between two $ signs as maths, both in the raw Markdown
    and again in the rendered page, and a \\$ escape does not survive that.
    Writing each $ as an HTML entity in its own <span> avoids both: the raw text
    contains no $, and on the page each $ sits in a separate element, which the
    maths renderer never pairs across.
    """
    parts = INLINE_CODE.split(line)
    for i in range(0, len(parts), 2):  # even parts are outside inline code
        parts[i] = parts[i].replace("$", "<span>&#36;</span>")
    return LINK.sub(fix_link, "".join(parts))


def markdown_to_cells(text: str) -> list[tuple[str, str]]:
    """Split a chapter into ("markdown" | "code", source) cells."""
    cells: list[tuple[str, str]] = []
    buffer: list[str] = []
    fence: str | None = None  # "python", "other", or None when outside a fence

    def flush(kind: str = "markdown") -> None:
        source = "\n".join(buffer).strip("\n")
        if source.strip():
            cells.append((kind, source))
        buffer.clear()

    for line in text.splitlines():
        if fence is None:
            if line.startswith("```python"):
                flush()
                fence = "python"
            elif line.lstrip().startswith("```"):  # may be indented inside a list item
                fence = "other"
                buffer.append(line)
            elif line.startswith("## "):
                flush()
                buffer.append(prepare_markdown_line(line))
            elif line.strip() == "---":
                continue  # cell boundaries already separate sections
            else:
                buffer.append(prepare_markdown_line(line))
        elif fence == "python":
            if line.startswith("```"):
                flush("code")
                fence = None
            else:
                buffer.append(line)
        else:  # inside a non-Python fence: keep verbatim
            buffer.append(line)
            if line.lstrip().startswith("```"):
                fence = None
    flush()
    return cells


def build_notebook(source: Path) -> nbformat.NotebookNode:
    header = (
        f"> 📓 **Notebook version of [`docs/{source.name}`](../docs/{source.name}).** "
        "Read top to bottom and run code cells with `Shift + Enter`. "
        "Before running a cell, try to predict what it will print.\n>\n"
        "> *Generated by `scripts/build_course_notebooks.py`: edit the Markdown file, then rebuild.*"
    )
    cells = [("markdown", header), *markdown_to_cells(source.read_text())]

    nb = nbformat.v4.new_notebook()
    for i, (kind, text) in enumerate(cells):
        cell = nbformat.v4.new_code_cell(text) if kind == "code" else nbformat.v4.new_markdown_cell(text)
        cell.id = f"{source.stem[:40]}-{i:03d}"  # stable ids so rebuilds produce identical files
        nb.cells.append(cell)
    # The same metadata JupyterLab writes when it saves a notebook, so opening and
    # saving a course notebook doesn't show up as a change in git. The version comes
    # from the interpreter running this script (the Docker image Jupyter also uses).
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3 (ipykernel)", "language": "python", "name": "python3"},
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": platform.python_version(),
        },
    }
    nbformat.validate(nb)
    return nb


def main() -> int:
    check_only = "--check" in sys.argv
    COURSE.mkdir(exist_ok=True)
    outdated = []
    for source in SOURCES:
        target = COURSE / f"{source.stem}.ipynb"
        content = nbformat.writes(build_notebook(source)) + "\n"
        if target.exists() and target.read_text() == content:
            continue
        outdated.append(target.name)
        if not check_only:
            target.write_text(content)

    if check_only and outdated:
        print(
            "Out of date (run: docker compose run --rm lab python scripts/build_course_notebooks.py):",
            ", ".join(outdated),
        )
        return 1
    action = "Checked" if check_only else "Built"
    print(f"{action} {len(SOURCES)} notebooks in course/ ({len(outdated)} changed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
